### ISSUE TITLE
Coverage for semaphore/index.ts shows errors

### ISSUE THREAD

**Issue by ComFreek** [ComFreek/async-playground#7]
[Coverage for `semaphore/index.ts`](https://comfreek.github.io/async-playground/coverage/semaphore/index.ts.html) shows error information, which also seems to decrease coverage percentage for no reason.

## How to reproduce

1. async-playground at commit fa32e5ef6e8e240b839309283b2368f1db6b8c38.
2. Optional: produce coverage info
3. Go to `coverage/semaphore/index.ts.html`. Live: https://comfreek.github.io/async-playground/coverage/semaphore/index.ts.html
4. The following error message is shown there:

    ```
    Cannot read property 'start' of undefined
    TypeError: Cannot read property 'start' of undefined
        at /home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:50:29
        at Array.forEach ()
        at annotateStatements (/home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:46:33)
        at Object.annotateSourceCode (/home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:190:9)
        at HtmlReport.onDetail (/home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:237:39)
        at Visitor.(anonymous function) [as onDetail] (/home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
        at ReportNode.Node.visit (/home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
        at /home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
        at Array.forEach ()
        at visitChildren (/home/travis/build/ComFreek/async-playground/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    ```

## Related bug reports

- https://github.com/istanbuljs/nyc/issues/733
- https://github.com/istanbuljs/nyc/issues/239
- https://github.com/istanbuljs/nyc/issues/677
- https://github.com/istanbuljs/nyc/issues/306
- https://github.com/gotwarlost/istanbul/issues/702

Summary:

- [x] Sometimes due to old Babel plugins being used. We don't use Babel here. (We only use TypeScript.)
- [x] Sometimes non-deterministic due to cached data. This is reproducible on Travis CI, which should not cache any data.
- [ ] Sometimes unsolved.

**Comment by ComFreek** [comment]
This seems to be magically resolved with Greenkeeper's PR #8.
